id: P006715
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 2021-12-17 12:18:50.975556
source_metadata:
  id: bdr:W1KG16706
  title: ཁ་སང་གི་རྨི་ལམ།
  author: ''
  volumes:
    0cb583ce65314aef8dd085cc5c56eff5:
      image_group_id: I2PD18261
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
